// types of action
export const Types = {
  SET_NAME: "SET_NAME",
  FETCH_QUESTIONS_SUC: "FETCH_QUESTIONS_SUC",
  FETCH_QUESTIONS_ERR: "FETCH_QUESTIONS_ERR",
  SET_QUIZ_TYPE: "SET_QUIZ_TYPE",
  SET_GIF: "SET_GIF",
  QUESTION_ANSWERED: "QUESTION_ANSWERED",
  QUESTION_ANSWERED_CORRECTLY: "QUESTION_ANSWERED_CORRECTLY",
  SET_CURRENT_QUESTION: "SET_CURRENT_QUESTION",
  ADD_RESULT_DATA: "ADD_RESULT_DATA",
  RESTART_GAME: "RESTART_GAME"
};
